### ISSUE TITLE
data disparity

### ISSUE THREAD

**Issue by Tim-Butterfield** [citycoins/protocol-api#6]
There seems to be some disparity in how much data is returned and of what type.  Here are a few examples:

https://protocol.citycoins.co/api/stacks/get-block-height - returns full JSON including redundant path and params

https://protocol.citycoins.co/api/ccd004-city-registry/get-city-id?cityName=mia - returns just the number in quotes "`1"`

https://protocol.citycoins.co/api/ccd005-city-data/is-city-activated?cityId=1 - returns the boolean `false`

I'm not asking about the specific values, but of the types of data returned and the differences between simple data and full JSON.  I would have expected the get-block-height function to be called regularly and have simple data also, but it didn't.

Is this an issue or expected behavior?

**Comment by whoabuddy** [comment]
Good catch! Most of this should be resolved in #4 and #5, and those little details are exactly what we need to know.

Will check back once both are merged.

**Comment by whoabuddy** [comment]
Ok so testing from #5 all should be resolved:

- https://fix-create-response-fn.protocol-api.pages.dev/api/stacks/get-block-height - returns just the block height now
- https://fix-create-response-fn.protocol-api.pages.dev/api/ccd004-city-registry/get-city-id?cityName=mia - returns `1` as a number, which is expected (MIA = city ID 1, NYC = city ID 2)
- https://fix-create-response-fn.protocol-api.pages.dev/api/ccd005-city-data/is-city-activated?cityId=1 - returns `false`, which is expected until ccip013-activation passes

Any other issues with return values?

**Comment by Tim-Butterfield** [comment]
The original is-city-activated now returns `City not found: 1`

**Comment by whoabuddy** [comment]
Yes - that's from the last PR, if nothing else to add we can merge the next PR and it'll behave the same as the preview links above. Just wasn't sure if there was anything else to add.

**Comment by Tim-Butterfield** [comment]
Going by the `fix` links, it now works as expected.  Thanks.
